apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-lab-application
  labels:
    app: gcp-lab
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gcp-lab
  template:
    metadata:
      labels:
        app: gcp-lab
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80
        readinessProbe:
            httpGet:
              path: /
              port: 80 
