apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-lab-application
  labels:
    app: gcp-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcp-lab
  template:
    metadata:
      labels:
        app: gcp-lab
    spec:
      containers:
      - name: gcp-lab-application
        image: asia-northeast1-docker.pkg.dev/satofumi-dev/public/gcp-lab-application:0.0.1
        ports:
        - containerPort: 8080    