apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcp-lab-application
  labels:
    app: gcp-lab
spec:
  replicas: 3
  selector:
    matchLabels:
      app: gcp-lab
  template:
    metadata:
      labels:
        app: gcp-lab
    spec:
      containers:
      - name: nginx
        image: nginx:1.14.2
        ports:
        - containerPort: 80