.PHONY: build push

build:
	docker build -t asia-northeast1-docker.pkg.dev/satofumi-dev/public/gcp-lab-application:0.0.1 .

push:
	docker push asia-northeast1-docker.pkg.dev/satofumi-dev/public/gcp-lab-application:0.0.1
